### ISSUE TITLE
Question: System Requirements self-hosted for Team of 50 members

### ISSUE THREAD

**Issue by bees4ever** [workadventure/workadventure#1158]
Dear WorkAdventure-Team,

thank you for providing this tool. Being as a team only remote connected needs some nice tools.

What for system requirements would you suggest for a self hosted instance, with a need that 50 people can access it at the same time without troubles?

Thank you very much
Ben

**Comment by moufmouf** [comment]
Hey @bees4ever,

For 50 people "only", a small machine will be enough to host WorkAdventure. Maybe 2 CPUs and 4 GB of RAM?
You might need a beefier machine if you are looking to host a Jitsi instance next to WorkAdventure (if you want to host your own meeting rooms). Also, you'll need a TURN server if you want people behind a firewall to be able to communicate via WebRTC with others.

**Comment by tabascoeye** [comment]
I have had 150 people on a VM with 2gb ram, single CPU. It's not a problem.
The load is on the TURN server and the jitsi server.
The WA containers are bored mostly

**Comment by bees4ever** [comment]
Thank you @tabascoeye and @moufmouf 

That helps me a lot! Should / Can I update the Readme with this notice. if this is of interest for other users, too?
