### ISSUE TITLE
Webpack watch is not recompling in Vagrant setup after file change

### ISSUE THREAD

**Issue by wachri** [workadventure/workadventure#1498]
I you have a setup like described in the readme with Vagrant the webpack file watcher doesn't recognizes file changes which are made on the host system. 
To get this working additional setup step is needed by installing  and using [vagrant-fsnotify](https://github.com/adrienkohlbecker/vagrant-fsnotify).
Probably this should also be added to the readme, or is there another better way?

**Comment by nolway** [comment]
We have deprecated the usage of webpack and vagrant
