### ISSUE TITLE
Suggestion to use squash commits

### ISSUE THREAD

**Issue by anbraten** [workadventure/workadventure#1822]
It seems as all of the official developers use pull-requests for adding features and externals are using them anyways. Currently the used merge strategy seems to be "merge commits". I would be interested to know if you thought about using [squashing](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits#about-squashing-a-commit) before and if you could think about changing the default merge strategy to be squashing for this project.

# Why?
Squashing allows bundle all PR commits into a single commit and to use the title of a PR as commit message (it can be extended and changed in a popup appearing on executing merge / squash). This has the huge benefit IMO that single commits of a PR are not visible in the `develop` branch at the end. Quite often developers are testing things by pushing commits with none descriptive messages which are reverted in the same PR directly. One additional benefit is that you could link the PR id at the end of the commit message so others could simply open and have a look at the PR and its comments introducing a change.

# How 
You could enable it in the general settings of this repository.
![Screenshot from 2022-02-03 18-17-56](https://user-images.githubusercontent.com/6918444/152394790-37ec6b72-e2c9-4be2-aa1e-b078d9ae1dc1.png)

**Comment by nolway** [comment]
We are now using squash for develop and master branches!
