### ISSUE TITLE
Profile page is displayed with error for "anonymous" user

### ISSUE THREAD

**Issue by albanbruder** [workadventure/workadventure#2066]
I have encountered the problem that if the user has never visited the /login page (and thus has no nonce  or state in her/his localStorage) the profile page is opened but an error is displayed. (see the screenshot)

![image](https://user-images.githubusercontent.com/36596731/162688249-f9ea0484-5842-4161-9b71-32b82a78506f.png)

I think this is due to [this](https://github.com/thecodingmachine/workadventure/blob/develop/pusher/src/Controller/AuthenticateController.ts#L178-L180) code. Before visiting the /login page the user has no nonce or state.

**Comment by gparant** [comment]
Hi @albanbruder, we've already fixed this error. We're testing in our staging version and this will be deployed in the next production deployment 💪
