### ISSUE TITLE
Tiled 1.9.0 introduces breaking changes in JSON map format

### ISSUE THREAD

**Issue by moufmouf** [workadventure/workadventure#2352]
The release of Tiled 1.9 introduced breaking changes in the JSON map format:

https://doc.mapeditor.org/en/stable/reference/json-map-format/#tiled-1-9

This has an impact on WorkAdventure maps since any map written with the new Tiled version won't work correctly (mostly for areas and variables as the way "objects" are stored has been modified).

We need to adapt WorkAdventure for this change while keeping compatibility with the old format.

Proposition:

- [x] Upgrade https://www.npmjs.com/package/@workadventure/tiled-map-type-guard to be able to read the new properties (and mark the "type" property as deprecated if possible)
- [x] Build a utility function (in tiled-map-type-guard ?) to copy properties from "type" to "class" and from "class" to "type"
- [x] Anywhere in the code where we read the "type" property", use "class" instead
  - [x] in front
  - [x] in back
  - [x] in scripting extra

**Comment by bjorn** [comment]
Until the map reader supports the "class" property in addition to the old "type" property, your users can also use the new "Compatibility Version" in the Tiled project:

<img width="687" alt="image" src="https://user-images.githubusercontent.com/531764/175967259-5cb84b11-415e-4a0b-aa9d-b92ed9a2ff7f.png">

When set to Tiled 1.8, the "type" property will be used when saving.

**Comment by moufmouf** [comment]
Hey @bjorn ,

I just realized that and was writing about it but you beat me by a few seconds.

Thanks a lot for the tip! (and thanks for Tiled!) :heart:
