### ISSUE TITLE
Feature Request: Make "Open back office" configurable

### ISSUE THREAD

**Issue by LindezaGrey** [workadventure/workadventure#2966]
Hey there!

At the moment the "hammer"-icon is hardcoded to workadventu.re
![image](https://user-images.githubusercontent.com/39629455/212950256-13d4273a-6b84-4db6-a252-7d4a2b7d0ea0.png)

https://github.com/thecodingmachine/workadventure/blob/08cf97a2b45393af3c992dc06410ec494ebbb4e3/play/src/front/Components/ActionBar/ActionBar.svelte#L277-L279

It would be nice to control it by env-variables or even better the admin-API
(In addition, there is a typo in "`_blanck`" -> should be "`_blank`"

best regards!

**Comment by LindezaGrey** [comment]
@gparant I saw that lochot already created a PR for this :)

https://github.com/thecodingmachine/workadventure/pull/2992

thanks a lot!

**Comment by lochot** [comment]
No probs, now, just waiting for approval :)

**Comment by lochot** [comment]
so, we will not merge this PR, because some better solution are posible, what do you think about @gparant @LindezaGrey ?

Moufmouf : 
> I'm looking at this PR and I wonder if we are not following the wrong path here.
> 
> This is not about your code (your PR is fine). This is about these lines:
> 
> [http://github.com/thecodingmachine/workadventure/blob/57c276133d9787f41a8844dfde22ebd5fe0dde69/play/src/front/Stores/GameStore.ts#L17-L22](https://github.com/thecodingmachine/workadventure/blob/57c276133d9787f41a8844dfde22ebd5fe0dde69/play/src/front/Stores/GameStore.ts#L17-L22)
> 
> Basically, the "Back office" menu is displayed only for users with the "admin" or "editor" tag. In my opinion, this rule is specific to our SAAS admin. Other admins might want to implement different rules.
> 
> So in my opinion, instead of checking the user tags in the front, we could change the "/api/map" endpoint in the API to return the URL of the "Open back-office" button.
> 
> This way, the admin could decide the URL. Even better: depending on the user profile, the link to the back office could point to different URLs.
> 
> For instance:
> 
> GET `/api/map`
> 
> Response:
> 
> ```
> {
>   // ...
>   "backOfficeUrl": "https://mybackoffice.com/user/[userid]"
> }
> ```
> 
> We can go even further. The link to "Register" is a special case of adding a button in action bar. We could make this even more generic. This way, we could add ANY button through the API. For instance:
> 
> GET `/api/map`
> 
> Response:
> 
> ```
> {
>   // ...
>   "actionBarCustomButtons": [
>     {
>       "type": "textButton",
>       "label": "Access back-office",
>       "url": "https://mybackoffice.com/user/[userid]"
>     },
>     {
>       "type": "iconButton",
>       "label": "Take a survey",
>       "src": "https://.../survey.png",
>       "url": "https://mybackoffice.com/survey"
>     }
> 
>   ]
> }
> ```
> 
Me : 
> Seems to be a good solution,
> 
> so if an admin_api_url, we can remove hammer button (and login and register too) and we add a new admin api/map field that can add button ?

**Comment by LindezaGrey** [comment]
@lochot nice suggestion i like it! this follows my idea when i mentioned "...or even better the admin-API"

**Comment by lochot** [comment]
@LindezaGrey , that's true !

Ok, i begin to work on this new PR

**Comment by moufmouf** [comment]
Closed by https://github.com/workadventure/workadventure/pull/3449#issuecomment-1685938178
