### ISSUE TITLE
Microphone connection issue

### ISSUE THREAD

**Issue by moufmouf** [workadventure/workadventure#3053]
A user could not connect her microphone.

Here is a screenshot of LogRocket showing the issue:

![image](https://user-images.githubusercontent.com/1290952/219035662-c40faa7d-c069-41fd-86c0-3afbd497aa8b.png)

It seems to be an "OvercontrainedError" happening when the microphone is selected.

Happens on Chrome / Windows.

**Comment by moufmouf** [comment]
I have no idea why this happens, but maybe relaxing the constraint on the Device ID from "exact" to "ideal" may relax the constraint?

![image](https://user-images.githubusercontent.com/1290952/219038280-6edd3a26-2052-457f-a45a-f80cd574ee86.png)

It's not really the best solution though...


Thoughts?

**Comment by moufmouf** [comment]
Note: could this apply if the microphone is grabbed by another application and not available to the browser?
Surprising, but might happen with the webcam!

**Comment by gparant** [comment]
I think it's more complex. On your screenshot, we can see that the id of Microphone is the same for the three devices ("Conexant SmartAudio HD"). So it's rather weird and I think that it's the problem when we try to select one device with the same id?

**Comment by LindezaGrey** [comment]
hey @moufmouf,
i sometimes have this problem and it can easily be reproduced. I use Nvidia broadcast to enhance my video quality. if i have the tool open to preview the applied effects the nvidia broadcast application has full control over the camera. in Workadventure the camera selection is then either not available, or this error appears:

![image](https://user-images.githubusercontent.com/39629455/226376146-8cf7889b-b1fe-4dbd-a9ef-c35fee92c7dd.png)

i also saw this behaviour at one of my teammates computer. he has a ton of video conferences going on and teams, webex and zoom installed. some program always catches his camera ;)
