### ISSUE TITLE
JitsiWidth not working anymore

### ISSUE THREAD

**Issue by moufmouf** [workadventure/workadventure#3060]
It actually seems not to be used in the code.

**Comment by froggr** [comment]
I'm new to workadventure - love it! Just noticed this bug and wondering if you should be using the jitsiWidth here: 
https://github.com/tabascoeye/workadventure/blob/0cb17c7fd1a9f815cd8d564d14047d2c2ada771a/front/src/WebRtc/JitsiFactory.ts#L163

**Comment by nolway** [comment]
Fix on the next release.
