### ISSUE TITLE
Sounds not bundled with map

### ISSUE THREAD

**Issue by moufmouf** [workadventure/workadventure#3079]
This issue actually belongs more to the map optimizer vite plugin.

I believe the plugin is not copying sounds in the "dist" structure.

Reported issue:

> The sounds stopped working in all of the maps that are stored in the new structure repos (with maps being in the "maps" folder). The mp3's are stored in the "public" folder (as before), but now the audio does not work on the map. Now all we see is the "Allow Audio" button, but when you click the sound doesn't work. We have tried linking the sounds in Tiled using all possible pathways, but we still could not get it to work.
>
> The sounds are working fine in the old-structure repos. 

<img width="1280" alt="Снимок экрана 2023-02-20 в 15 23 38" src="https://user-images.githubusercontent.com/1290952/220158371-b8a453be-e009-4bdc-9d8f-0b5a1375f0df.png">

**Comment by Pepe17031** [comment]
I encountered a similar problem, I was able to solve it by duplicating the folder "maps" with attached sounds in the folder "public"
