### ISSUE TITLE
Error presence indicator

### ISSUE THREAD

**Issue by gparant** [workadventure/workadventure#3106]
<img width="564" alt="Screenshot 2023-03-01 at 17 14 38" src="https://user-images.githubusercontent.com/23724509/222199951-c4d96f49-1cde-43e2-9b8f-009ff418fcc4.png">

**Comment by LindezaGrey** [comment]
Hi there, i am running a v1.15.1 version and the indicators are all over the place 😆 
![Unbenannt](https://user-images.githubusercontent.com/39629455/222739353-86d58581-4356-44c0-b245-64a3163f1ca5.PNG)

My woka (Andy) is correctly shown.
"Seko" is not shown in the user list
Jan is green but shown orange in the userlist
Max is shown green in the userlist but is red on the map
Marko has no icon

There are no errors logged in ejabberd/play/back. Browser console looking good.
