### ISSUE TITLE
Tiles entries are not working

### ISSUE THREAD

**Issue by ValdoTR** [workadventure/workadventure#3152]
I created an "entries" layer with a `startLayer` (bool) property set to true.
In this layer I put tiles that had `start` (string) custom properties, with some values.

When I try to access my map on one of the entries with the # hashtag my Woka is spawning on the default positions anyway. So I think this feature is broken.

https://workadventu.re/map-building/entry-exit.md#content-defining-several-entry-points (search for "You can also use the tiles properties to create entry point.")

**Comment by highno** [comment]
Totally works for me. I have the standard start layer but created a set of additional start tiles. Each has a start attribute (type String) and has been given a unique start tag by me. I drop these tiles on the start layer and have perfect addressable start points.
