### ISSUE TITLE
Mix of languages

### ISSUE THREAD

**Issue by HugoAverty** [workadventure/workadventure#3172]
Some of the texts are in English other in French.
![Capture d’écran 2023-04-06 à 09 23 09](https://user-images.githubusercontent.com/1681508/230304336-1bcead91-c2f4-4229-8c04-11b3319ca28d.png)

**Comment by Waclaw-I** [comment]
Probably there are no French keys defined so it takes it from English ones.
I guess once all keywords are defined, we can go through them and fill up other languages.
