### ISSUE TITLE
[MAP EDITOR] Holding SHIFT while editor is closed is 'working'

### ISSUE THREAD

**Issue by ValdoTR** [workadventure/workadventure#3283]
If I close the map editor and I hold the SHIFT key, my couch becomes orange. This should happen only when the map editor is open and a entity is selected.

Without SHIFT key
![Capture d’écran du 2023-06-09 16-36-40](https://github.com/workadventure/workadventure/assets/14997703/5ce604a0-46e2-45c5-b114-f19caaacbdc7)

With SHIFT key
![Capture d’écran du 2023-06-09 16-36-03](https://github.com/workadventure/workadventure/assets/14997703/1876524e-1eb7-49fc-8c0f-63588819d785)

**Comment by gparant** [comment]
Fixed in the last version 💪
