### ISSUE TITLE
Play Audio on fresh loading map

### ISSUE THREAD

**Issue by lochot** [workadventure/workadventure#3291]
I don't know if it is reliable to  #3284, 
but since last update, when making an audio zone on a start zone, audio will not play, walking out of the audio zone and return in will play the audio

**Comment by cesar-cardinale** [comment]
Hello, as you can see, if you go to our team map (https://play.staging.workadventu.re/@/tcm/workadventure/wa-village) you will see that when you are spawning in a silent zone, you are in silent mode. 

Is your silent zone created in the Map Editor or via Tiled file?

**Comment by lochot** [comment]
For information, map is from tiled, but you are right, problem is solve (except for my map, but on other map all is ok, so i will inspect it)
