### ISSUE TITLE
[MAP EDITOR] Entities depth changes over time

### ISSUE THREAD

**Issue by ValdoTR** [workadventure/workadventure#3292]
Not sure how and when this is happening but sometimes some of the entities placed on tables are changed from 'above' to 'below' the table.
This happens when I'm placing other entities, maybe when I use the CTRL key to replace entities.
![image](https://github.com/workadventure/workadventure/assets/14997703/7d912161-7f56-454b-952b-053308e0c80b)

The coffee machine on the bottom part was first placed above the table, and is depth has been changed by the software.

**Comment by gparant** [comment]
May not happening again, the last version deploy should fixed this issue 🙏
