### ISSUE TITLE
Why are collisions marked orange now - and how to disable it?

### ISSUE THREAD

**Issue by netzwerkgoettin** [workadventure/workadventure#3320]
Hi folks,

after getting `1.15.12` finally running, I stumbled upon the next question: all my collisions have some kind of an orange overlay which is really disturbing.

<img width="50%" alt="Screenshot 2023-06-18 at 16 59 25" src="https://github.com/workadventure/workadventure/assets/11242139/b4475451-c786-48d4-bc17-d32471165394">

I thought it a map problem, but after a while I tried the map @moufmouf mentioned in #3309. Its collisions also are marked orange.

<img width="50%" alt="Screenshot 2023-06-18 at 17 01 21" src="https://github.com/workadventure/workadventure/assets/11242139/43644a0f-679d-4808-8d2a-0da4c40139ad">

How can I disable this? Since it seems not to be a map problem, I searched on server side. But I didn't find anything suitable...

Thanks a lot,
  Marianne

**Comment by LindezaGrey** [comment]
Check that the env variable DEBUG_MODE is set to false

**Comment by netzwerkgoettin** [comment]
😭 *banging head against desk*

Thank you so much!
