### ISSUE TITLE
[Map editor] Jitsi configuration pop up

### ISSUE THREAD

**Issue by moufmouf** [workadventure/workadventure#3365]
The Jitsi configuration popup makes absolutely no sense.

The dropdown was supposed to be usable to add or remove fields dynamically. In practice, it is not working as all fields are displayed.

I'm wondering if we should not drastically simplify this.

![image](https://github.com/workadventure/workadventure/assets/1290952/36a8c7de-52c4-4dbf-b719-8e9818564c0a)

**Comment by gparant** [comment]
De nouveaux paramètres ont été ajoutés sur cette page et sont utiles aujourd'hui 💪
