### ISSUE TITLE
[Calendar] Impossible to configure a Meeting, submit button is disabled

### ISSUE THREAD

**Issue by jacquesbh** [workadventure/workadventure#3395]
Hi!

When I configure a meeting I arrive on the form where I can select the room. The select is empty and that's fine.

But once I fill it, the Update Meeting button becomes disabled and I can't save my form.

![calendar](https://github.com/workadventure/workadventure/assets/858611/433c4d90-3434-4e00-93fe-c7a8276c9737)

**Comment by moufmouf** [comment]
Ho gee!

This is what happens when you refactor without types and tests :facepalm: 

This should be fixed. And this part of the code is now properly tested.
Thanks  for the feedback!
