### ISSUE TITLE
[Map Editor] unprotected /maps Endpoint

### ISSUE THREAD

**Issue by LindezaGrey** [workadventure/workadventure#3399]
Maybe security / sensitive data related, but i guess partially on purpose:

The map-storage container exposes a /ui route for map uploading. Even though deletion/modification and creation is protected by authentication, everybody has the possibility to see all available maps.
E.g. on the official servers:

https://workadventure-90.map-storage.staging.workadventu.re/ui/

I know that each map can be protected and put behind auth, but it could be a potential risk if everybody knows all the available maps. In addition to that, the **area editor** also queries the /maps endpoint of the map-storage container to fill the possible worlds for an exit.

![image](https://github.com/workadventure/workadventure/assets/39629455/b4716d10-5b29-4dab-98c0-8392fedfa6fe)

This could be solved by using the "/room/sameWorld" endpoint of the admin-api (maybe this is already on your roadmap)

**Comment by moufmouf** [comment]
Well, I think you understood what is going on.
We need the /maps endpoint to be available to all the users of the area tool in the map editor.

> This could be solved by using the "/room/sameWorld" endpoint of the admin-api (maybe this is already on your roadmap)

We can't really do this, because that would make this feature unavailable to all the users who are self-hosting without an admin.

**Comment by LindezaGrey** [comment]
I see! I wonder how you plan to manage the following scenario (again, i am still trying to understand how everything should work out with the new update):
Imagine you have 2 paying customers CompanyA and CompanyB. they "live" in two seperate worlds:

/@/companyA/myworld/hq
/@/companyB/myworld/companyname_strategic_meeting

wouldn't CompanyA see an exit room called "companyname_strategic_meeting"? This scenario is something i would like to avoid. Also couldn't CompanyB troll companyA by creating a map with the name "hq", thus overwriting the .wam file? In my admin-api i dynamically create the wam file name with the userid in front of the actual map name to avoid duplicate names (e.g. 15-mymap.wam)

So to make this possible for admin-api users and keeping this feature for normal self-hosting users, how about setting this url as an env variable? maybe something like "GET_EXIT_MAPS_URL" which defaults to map-storage/maps. An admin-api user could set this to ADMIN_API_URL/room/sameWorld or something else .A query parameter with the current playUrl would be enough to filter for eligible maps in the admin-api. What do you think?

**Comment by moufmouf** [comment]
We deal with this in a different way. Because the map-storage can be used to host HTML files and JS files, we did not want to have a local-storage or cookies from the map-storage domain shared between worlds.
So each world gets its own map-storage domain name. If you look at the env variables of the map-storage, there is a setting to turn on a "multi domain" mode. In this setting, each world gets its own domain and thus, the "/maps" endpoint is restricted by domain name.

**Comment by LindezaGrey** [comment]
ah got it! interesting... this would indeed solve the headache i got. i will check it out, for now i close this issue :) thank you!
