### ISSUE TITLE
Headset parameters is forgotten in 1.16.5 after a refresh

### ISSUE THREAD

**Issue by DstnyWorkAdventure** [workadventure/workadventure#3435]
We tested 1.16.5 and compared to workadventu.re, the microphone (and headset) settings are not kept if we refresh the web page go back. This means the user needs to reconfigure the heaset each time they talk.

Step to reproduce:

Change the settings in the bubble:

<img width="200" alt="image" src="https://github.com/workadventure/workadventure/assets/115720422/e3252a1f-aad6-4a91-a93b-f19d638b3f8e">

After a reload

<img width="226" alt="image" src="https://github.com/workadventure/workadventure/assets/115720422/8b5b42bb-7581-45eb-a700-abb47b5b0c99">

It is also ín workadventu.re:

<img width="211" alt="image" src="https://github.com/workadventure/workadventure/assets/115720422/b580c611-9cf1-4f01-9a04-500459405f9f">

And when we refresh

<img width="207" alt="image" src="https://github.com/workadventure/workadventure/assets/115720422/79d6ebd9-1c67-4dee-8715-a4bc51e69612">

**Comment by nolway** [comment]
Thank you for your feedback, we will fix this issue soon as possible.
