### ISSUE TITLE
how to use b2cLogin in signup workadventure

### ISSUE THREAD

**Issue by cleberazevedo** [workadventure/workadventure#3438]
how to use b2cLogin in signup workadventure or your config settings?

**Comment by nolway** [comment]
Hello, SSO authentcation is only available on the [SAAS ](https://workadventu.re) and not on the open source project.

**Comment by gparant** [comment]
Hello @cleberazevedo, it's possible to use it with open source project: https://github.com/workadventure/workadventure/issues/2794
