### ISSUE TITLE
strange things with variables

### ISSUE THREAD

**Issue by lochot** [workadventure/workadventure#3441]
Hello here, i have a strange problem with variables. 
On a lot of my map, i use variables and all is ok, but with two maps, variables seems to be not presents 
when i use with scripting API
```javascript
WA.state.saveVariable('name','value')
```

and the same happen with room api, when i read a variable on thoses map the return is 
```bash
{
   nullValue: undefined,
   numberValue: undefined,
   stringValue: undefined,
   boolValue: undefined,
   structValue: undefined,
   listValue: undefined
 }
```
the same code is used on all my maps, but don't work only on two, like variables are not existing on those maps, anybody has encounter this ?

Note, the variable are used in the map like a variable "myvar1" is used to open a website with {{{ myvar1 }}} and the result is ok, but i can't read them or modify them on the two maps

**Comment by moufmouf** [comment]
Ho, this is really weird. I've never seen that in the past.

Do you persist those variables?

On the map that is failing, is it failing both with `{{{ myvar1 }}}` and when you simply do a `console.log(WA.state.myvar1` ?

**Comment by lochot** [comment]
console.log(WA.state.myvar1) give me :
```bash
state myvar1
```
if i try just after 
```javascript
WA.state.saveVariable('myvar1', 'test').catch(e => console.error('Something went wrong while saving variable'));
```
workadventure loop reboot , in my logs, it say that we can save a variable that is not declare as an object on the map, but it is an object
you can see it here https://play.wa.d-n-d.fr/_/global/maps.lochot.com/dnd/lochottest.json

**Comment by lochot** [comment]
Ok i change persist true with persist false, and all is ok.
I am affraid that i did not understand what the persistence do....

**Comment by moufmouf** [comment]
This is weird. It should be working...
Does it happen again when switching persistance to true again?

If yes, maybe the good idea it to have a look at the Redis database itself and looking how data is stored there.
That would help me pinpointing the issue. The key consists of the room name + the variable name.

**Comment by lochot** [comment]
ok, i will try this and comment what will happening

**Comment by lochot** [comment]
News from today :
In redis i create the key named with the failed map name, and i delete it, i refresh my browser with wa on this map and TADA, in redis my keys is on, and when i change var content, it appear in the key's values.
I will try on a second server and let you know if it works (var on failed map are in persist true)

**Comment by moufmouf** [comment]
Weird.
It somehow looks like a cache issue. WorkAdventure is caching the Tiled map server-side to know which variables are available. If the cache is not purged, it could behave a bit like this.
But the cache is only in memory. So rebooting the server should solve the problem. Did you try to restart the server to see if the problem is fixed?

**Comment by lochot** [comment]
Ok,
lot of time and no result : 
- on two servers same map -> nothing in redis (no keys for this map) 
- in redis i can see an other map with persistent variable
- I reboot the server and relaunch workadventure -> no change
- i remove persist from variable and re make them persist -> no change

At this moment, i know that the problem does not come from variables scripting, but from the non saving in redis so i tried to understand what happen and see that workadventure check all layer if it is an objectgroup
mine are objectgroup in folder, i move them at root of project -> no change

i continue
