### ISSUE TITLE
Old admin links need to be changed

### ISSUE THREAD

**Issue by ValdoTR** [workadventure/workadventure#3455]
When clicking on "Try the map" button from a room popup in the admin, the user goes to `play.admin.wokadventu.re` instead of `play.wokadventu.re`
[try the map link issue.webm](https://github.com/workadventure/workadventure/assets/14997703/980e4953-6030-4d11-9f4e-81a35554f9e9)

When clicking on the back office button from a map, the user goes to `wokadventu.re/admin` (which leads to a WP page) instead of `admin.wokadventu.re`
[back office link issue.webm](https://github.com/workadventure/workadventure/assets/14997703/e5202b8b-3cb7-4ba5-99f0-fc15624ac6d7)

**Comment by moufmouf** [comment]
Thanks! Both have been modified and will be fixed with the next redeploy.
