### ISSUE TITLE
OIDC with Single Domain Config

### ISSUE THREAD

**Issue by Lurkars** [workadventure/workadventure#3513]
Just small notice, that the domain check fail on OIDC login when PUSHER_URL is not manually adjusted in 
https://github.com/workadventure/workadventure/blob/develop/contrib/docker/docker-compose.prod.yaml#L39

**Comment by moufmouf** [comment]
Good catch!

I guess we could configure it to:

```
PUSHER_URL=https://${DOMAIN}/
```

Let me try!

**Comment by moufmouf** [comment]
Closed by #3540
