### ISSUE TITLE
New Helm chart

### ISSUE THREAD

**Issue by klauserber** [workadventure/workadventure#3534]
Hello, this is not an issue but an information.

We use Workadventure for about 3 months and we are really enjoy ist. Thank you very much for the great software!

We run it in Kubernetes and since I found no up to date deployment method on the web, I decided to write a new Helm chart: https://github.com/klauserber/workadventure-k8s

It is an adaption of the docker-compose deployment method (at https://github.com/workadventure/workadventure/tree/master/contrib/docker) and should be fairly easy to extend and maintain.

May be it make sense to place a link somewhere, if it is interesting for some folks here.

**Comment by moufmouf** [comment]
Hey @klauserber !

Excellent! Thanks a lot for sharing :heart: 

If you want, you can put a link in the production install documentation in this chapter: https://github.com/workadventure/workadventure/tree/master/contrib/docker#installation-method-for-the-workadventure-server

Also, you can open a PR in the awesome-workadventure directory: https://github.com/workadventure/awesome-workadventure/

**Comment by klauserber** [comment]
@moufmouf Thank you for the pointers.

Here are the PRs:

https://github.com/workadventure/workadventure/pull/3548
https://github.com/workadventure/awesome-workadventure/pull/5

**Comment by klauserber** [comment]
Nobody has merged my PRs. That is a pity. What I'am doing wrong?

**Comment by moufmouf** [comment]
Oops, sorry! I wanted to rephrase your changes to make it clear the core team is not provided any support on this installation method (we have already enough questions on the installation method we do support :laughing:  )

Working on that now!

**Comment by moufmouf** [comment]
Merged!
Thanks for the PRs and sorry for the time it took to merge them!
