### ISSUE TITLE
New camera/microphone code problematic when settings are stored but hardware is "changing"

### ISSUE THREAD

**Issue by zobadaniel** [workadventure/workadventure#3564]
I have trouble describing a way to reproduce the issue, but let me describe it anyway:

First, the improved way for camera+mic selection work better. So far, so good.

I see an issue with permanently storing the selection, and then chaning the hardware (removing laptop from a dock / port replicator, connecting to different port replicator). If the camera / mic I chose earlier is permanently "gone", I sometimes have no way to select alternative devices. Refreshing the page won't help.

The only way is to lose all settings by clearing cache / cookies. This is unfortunate, as it also resets settings which I need to apply again (language, away mode, ...)

I hope you can reproduce this with, say, a USB camera.

**Comment by moufmouf** [comment]
Hey @zobadaniel ,

On what version of WorkAdventure is this happening?
I think I solved this issue last week (maybe on Thursday or Friday). Can you confirm the issue still happens on the "master" branch?

**Comment by zobadaniel** [comment]
@moufmouf It was definitely happening on my v1.17.4 deployment. Unsure if I ever saw it recently on one of my workadventu.re hosted maps. Let me update my own instance to v1.17.7 and check again.

**Comment by zobadaniel** [comment]
@moufmouf I can now unfortunately report that it still happens with 1.17.7. Moving between one port replicator at home and one at the office, I'm getting "access to camera denied", but no option to select a different one. Refreshing the page doesn't help, and going to camera/mic settings explicitly doesn't help either.

**Comment by zobadaniel** [comment]
Removing "preferredAudioInputDevice" and "preferrecVideoInputDevice" from local storage and then refreshing helps, it brings me back to the input device selection dialogue after I refresh the page, and now the current devices are being offered.

**Comment by moufmouf** [comment]
@nolway can you take a look?

**Comment by moufmouf** [comment]
I think we got it!
It was hard to reproduce.... until we realized it is a Firefox issue!

This should close the issue for good: https://github.com/workadventure/workadventure/commit/2c4544186cd2aebaa6e3c2db1114499ce8fd4fa8

Will be tagged with the next release.
Thanks for reporting this @zobadaniel !
