### ISSUE TITLE
[MAP EDITOR] Removing the "silent" feature of an area doesn't work

### ISSUE THREAD

**Issue by ValdoTR** [workadventure/workadventure#3585]
When you created an area and make it silent with the map editor, after clicking on the "X" to remove the feature, you are still in a silent zone even after leaving the area.

[Screencast from 26-10-2023 15:25:27.webm](https://github.com/workadventure/workadventure/assets/14997703/64cd775a-3180-4e37-a58f-2c0aadd6f4fb)

The correct beahaviour would be to exit the silent zone mode after removing the feature.

**This exact same feature (setting/removing a silent area on demand, with wokas inside it) is requested and will be used soon.**

**Comment by gparant** [comment]
Fixed in the last version 💪
