### ISSUE TITLE
Bug with the "Allow Audio" button

### ISSUE THREAD

**Issue by pescudie** [workadventure/workadventure#3651]
Hi, 
I added sound via the workadventure interface on zone or I also tried via Tiled but I have the same problem each time on Google Chrome I have the "Allow Audio" button which it is not not possible to click to authorize and therefore the music does not play. I don't understand why, is this a bug?
Thank you,
Pierre

**Comment by LindezaGrey** [comment]
this button also appears when the link points to an invalid audio file (e.g. to something that cannot be played back natively by the browser). Which link are you putting into the zone?

**Comment by pescudie** [comment]
I put a link that points to an mp3 file hosted on a WordPress site.  The link ends with .mp3

**Comment by moufmouf** [comment]
Another important thing I think: the CORS headers must be set on the MP3 file.

Do you see anything special in your browser console or network tab when you try to play the file?

**Comment by pescudie** [comment]
I tried with this file : https://www.elaborha.fr/wp-content/uploads/2023/12/cafe.mp3

It is hosted on our own server and I added a directive in the htaccess to Header set Access-Control-Allow-Origin.
Something that I had not done before but it still does not work currently, when I add music via the workadventure interface, I paste the link but in the input text it does not keep it.

When i add the link : 
![image](https://github.com/workadventure/workadventure/assets/153516380/8fd76524-ec5a-4050-8002-23e2e4161044)

when I click on the area again, the link disappears :
![image](https://github.com/workadventure/workadventure/assets/153516380/a2fb9038-b392-4e72-b0e9-9823923e9bfa)

**Comment by pescudie** [comment]
by having activated "Access-Control-Allow-Origin" on the htaccess of our server I can play the audio via a zone defined via Tiled. On the other hand, when I create a zone using the workadventure interface directly, I always have the problem mentioned above.

**Comment by moufmouf** [comment]
>  when I add music via the workadventure interface, I paste the link but in the input text it does not keep it

This is a bug we have already fixed (https://github.com/workadventure/workadventure/pull/3613). It will be released in production within 2 weeks I think!
