### ISSUE TITLE
[MAP EDITOR] Entry point overridden on an exit area 

### ISSUE THREAD

**Issue by ValdoTR** [workadventure/workadventure#3657]
I set up an exit area with a specific destination entry, but when I blur the area and click on it gain it loads with the last entry in the list no matter what.
![image](https://github.com/workadventure/workadventure/assets/14997703/f332f3b6-11d4-47e5-b637-891eddb5d22c)
Here the `hse` is always selected after clicking on my area.

To reproduce:

1. Create a map A with several entries
2. Create a map B with an exit that points to one of the map A entries
3. Blur the map B exit area and click on it again, you will see that the entry selected is always the last one in the selector.

**Comment by moufmouf** [comment]
Fixed in #3658
