### ISSUE TITLE
How to remove amazonaws

### ISSUE THREAD

**Issue by t10r** [workadventure/workadventure#3686]
Hi,

is there an easy way to remove the dependencies to the amazonaws. I would like to have a local workadventure without any connections to external services.

Kind regards
     Tim

**Comment by moufmouf** [comment]
Hey Tim,

Not sure what you are talking about. There is no mandatory connection to AWS in any way. You can store data in a S3 compatible storage, but nothing mandates you to use Amazon S3. You can use minio for instance which is compatible with the S3 protocol and can be self-hosted.

**Comment by t10r** [comment]
Sorry, I can't reproduce it at the moment but I had the case that a connection to amazonaws was created.
