### ISSUE TITLE
1.18.x: User properties (texture, optionally name/woka) are not asked/saved when using OpenID login without compatible AdminAPI 

### ISSUE THREAD

**Issue by Kishi85** [workadventure/workadventure#3698]
Since 1.18.0 Workadventures can store Name, Texture and Woka properties using the AdminAPI if a user is logged in.

If no AdminAPI (or one without the necessary capabilites) is present but a OpenID login is configured (and enforced) the User properties are no longer stored in the local browser storage due to multiple checks like these with the code (see PR#3609 and PR#3610)
```
...
// Only save the name if the user is not logged in
        // If the user is logged in, the <property> will be fetched from the server. No need to save it locally.
        if (!localUserStore.isLogged()) {
...
```
Also if no User properties can be loaded the name from OpenID is used for the username with a ghost character as its texture.

What should happen: If a (OpenID) Login and no AdminAPI (or an AdminAPI without the necessary capabilities) is present then the old way of storing the user properties within the browsers local storage should be used.

**Comment by moufmouf** [comment]
Hey @Kishi85 !

Thanks for reporting this in a detailed way!
This should hopefully be fixed by https://github.com/workadventure/workadventure/pull/3700
