### ISSUE TITLE
JS script loaded from CDN violates GDPR

### ISSUE THREAD

**Issue by pizkaz** [workadventure/workadventure#3843]
This line loads klaxoon.js from AWS:
https://github.com/workadventure/workadventure/blob/23f3e25df9e833d4eea3ae0119a3df979f5f3663/chat/index.html#L43

Is it possible to bundle it?
In any case we should probably load it only if `KLAXOON_ENABLED=true` in .env, right?

**Comment by gparant** [comment]
Hello, this script is our bundle hosted on our CDN 💪

You are right, we could load this script only if `KLAXOON_ENABLED` is true. We haven't renderer for the chat service today. But WorkAdventure's next update will include the import of chat into the core project and Klaxoon script charges only if the environment variable is set to true.

**Comment by pizkaz** [comment]
Hmm in the current Workadventure version this is still an issue. Maybe it was overlooked?

**Comment by pizkaz** [comment]
It's gone in the `develop` branch, so I guess it will be fixed with the next release. :smiley:
