### ISSUE TITLE
Map Explorer Search and Highlight broken

### ISSUE THREAD

**Issue by gparant** [workadventure/workadventure#3904]
I can't locate items or zones in the list of the map editor or on the map when I try to search for it.
 - When a user hovers an object or zone in the map explorer, It should be highlighted and the camera moved on the item or zone with the best zoom to see where it is.
- The user is unable to view the zone on the map when the map editor is opened.

https://github.com/workadventure/workadventure/assets/23724509/59e76164-7378-4384-8693-54eb64be7449

**Comment by moufmouf** [comment]
Closed by #3905
