### ISSUE TITLE
After changing my status in a silent zone the woka skin changes

### ISSUE THREAD

**Issue by ValdoTR** [workadventure/workadventure#3924]
Funny but still a bug: when opening the status menu and choosing a status while passing by a silent zone, the front freezes with this error:
![Capture d’écran du 2024-05-06 16-32-57](https://github.com/workadventure/workadventure/assets/14997703/07dd7e45-5a43-4c2d-95e4-1611b526112e)
Then, after reloading, the skin of the woka changes randomly.
After each reload the woka changes:
![Capture d’écran du 2024-05-06 16-33-31](https://github.com/workadventure/workadventure/assets/14997703/65bbe75f-ceb9-4ae5-8343-b704b4ca301a)
![Capture d’écran du 2024-05-06 16-33-59](https://github.com/workadventure/workadventure/assets/14997703/7ad693e2-4aa6-4fae-aa02-a797b1227b32)

**Comment by moufmouf** [comment]
I think this was fixed yesterday. Is this still happening in staging right now?
