### ISSUE TITLE
Basic question:  How to update Workadventure? or is updating not necessary?

### ISSUE THREAD

**Issue by Teufelskomet** [workadventure/workadventure#3932]
First of all: I am not a coder and have painstakingly familiarized myself with Tiled. I created my map in 2022 with Tiled based on the starter kit from 2022 created. In the meantime there are new versions of WorkAdventure, currently v 1.19.

My question: do I have to update my map manually? Is a version update automatically applied to existing maps?

**Comment by moufmouf** [comment]
Hey @Teufelskomet ,

We do our very best to keep an upward compatibility for your maps. So if you designed your map in 2022, it should still work in 2024.
As of now, we have not issued any deprecation warning for any of the Tiled properties. If you have been using the scripting API, there are a few deprecated features listed here: https://docs.workadventu.re/developer/map-scripting/references/api-deprecated
