### ISSUE TITLE
[Map Editor] Improve the understanding of the collision system.

### ISSUE THREAD

**Issue by Citronart** [workadventure/workadventure#3993]
The difference between the collision system and the management of layers above the woka is not intuitive.

WIP 
![IMG_5990](https://github.com/workadventure/workadventure/assets/113022277/86355bec-4ed3-4819-b642-620adcb8350f)

**Comment by gparant** [comment]
Have you an idea?

**Comment by matthintosh** [comment]
Description and collision logo in legend are added in my PR.
