### ISSUE TITLE
Check quests button not working

### ISSUE THREAD

**Issue by ValdoTR** [workadventure/workadventure#4146]
When we unlock a badge and click on the 'Check quests' popup button, we are not showing the quests menu but the contact menu instead.

![image](https://github.com/user-attachments/assets/eec7f325-4018-413e-b75a-8e01dc724475)

Here is what I see in the console:

![image](https://github.com/user-attachments/assets/78e7ef99-ad94-4ef5-8f5d-00f5e5554569)

![image](https://github.com/user-attachments/assets/0455c6f2-e9ff-4005-a4be-13bf2f39faff)

**Comment by gparant** [comment]
Fixed with the laster version 💪
