### ISSUE TITLE
pastille pour dernier message

### ISSUE THREAD

**Issue by gregr4** [workadventure/workadventure#4203]
<img width="256" alt="Capture d’écran 2024-09-13 à 14 27 37" src="https://github.com/user-attachments/assets/64b8ffc0-f10a-42bd-94ce-158f04b618ad">

quand on reçoit un message en DM ou groupe il faut que le contact ou le groupe apparaissent en premier dans la liste

**Comment by moufmouf** [comment]
Déjà fait :)
Ca va être déployé dans quelques minutes.
