### ISSUE TITLE
Self-hosted Proximity Meeting Audio and Video didn't work on v1.21.x.

### ISSUE THREAD

**Issue by gefisanjaya** [workadventure/workadventure#4267]
I completely installed Coturn, and use my useable subdomain (with Caddyfile). I followed [this tutorial](https://meetrix.io/blog/webrtc/coturn/installation.html) then test the Turn Server and it says Reachable. But somehow when i set TURN_SERVER on .env, the WebRTC won't work and throw errors. 

After discussing it with @TheUnknownDad at Discord's DM, he suggest me to try using release version not master. And the Proximity Meeting is working on v1.20.2 with the same configuration. 

This is my configuration on .env that i didn't change before and after "Downgrading"  version:
```
TURN_SERVER=turn:<mydomainname>:3478
TURN_USER=
TURN_PASSWORD=
TURN_STATIC_AUTH_SECRET=<static_auth_secret>
STUN_SERVER=stun:<mydomainname>:3478
```

**Comment by moufmouf** [comment]
Hey @gefisanjaya ,

Did you try v1.21.1 ?
Is it broken with v1.21.1 but working with v1.20.2?

**Comment by gefisanjaya** [comment]
Yes i did, and I don't know why.

**Comment by gefisanjaya** [comment]
My bad, after i upgrade to 1.21.1. That's completely my mistake.
