### ISSUE TITLE
My screens won't turn off or go on screen saver while using WorkAdventure

### ISSUE THREAD

**Issue by sohrabsardari** [workadventure/workadventure#4269]
Hi folks,

I have configured my Windows power options to turn off the screen after 5 minutes of inactivity and activate the screen saver after 1 minute. (I have implemented these settings because of energy consumption and to prevent burn-in on my OLED monitor.)

However, when I am actively using WorkAdventure, my screen does not turn off or activate the screen saver as expected. (My screen is always active and it's preventing the screen from entering idle mode.)

I am using Windows 11 64-bit with Google Chrome version 129.0.6668.59.

**Comment by moufmouf** [comment]
Hey @sohrabsardari !

Interesting! We are indeed using "screen wake locks" to prevent the screen from going into power save mode, but those should only happen if you are inside a bubble or a Jitsi.

I guess this is happening even if you are not in a bubble or a Jitsi?

What version of WorkAdventure are you using? Is this the SAAS version (hosted on play.workadventu.re?) or is this a self-hosted install? (and if so, what is the version number?)

**Comment by sohrabsardari** [comment]
Hi @moufmouf 
I'm using the SAAS version. And yes, I've noticed that this issue occurs even when I'm not in a Bubble or Jitsi call.
