### ISSUE TITLE
error Forgot Password

### ISSUE THREAD

**Issue by klinshy** [workadventure/workadventure#4314]
`Failed to load resource: the server responded with a status of 500 ()`

![Screenshot of App Brave Browser in Window Server Error Date 2024-10-14 at 07-12 001032@2x](https://github.com/user-attachments/assets/6c8656a9-8231-4f50-b66c-edc7b626d29a)

**Comment by moufmouf** [comment]
Hey Kilian,

This error seems to be related to your SMTP server settings. Did you change those recently, or is it possible that your SMTP server was down when you tried this?

**Comment by klinshy** [comment]
Oh yes David, you are absolutely right. It appeared just to my mind that we have updated our Mail Account Password and havent updated the SMTP Setting in WoAd. Thank you!

I can confirm that password resets are working perfectly fine and are whitelabeled.
