### ISSUE TITLE
api-nav.md Typo getCoWebSites

### ISSUE THREAD

**Issue by klinshy** [workadventure/workadventure#4365]
![Screenshot of App Brave Browser in Window CoCreationWorld Date 2024-10-29 at 15-04 001217](https://github.com/user-attachments/assets/1dc4ee08-c381-4de1-ab34-df166ec5ac2a)

should be WA.nav.getCo**W**ebSites

![image](https://github.com/user-attachments/assets/a91af27e-46b5-4c58-a255-8903380fc57a)

**Comment by moufmouf** [comment]
And the award of the best issue goes to....
![image](https://github.com/user-attachments/assets/4f7fd061-5c8d-4877-8888-cbbd0187df8a)

@klinshy of the house of Grifindor!

Will be fixed :D

**Comment by klinshy** [comment]
Thank you Professor.
