### ISSUE TITLE
1.22.1 still breaks OIDC

### ISSUE THREAD

**Issue by klauserber** [workadventure/workadventure#4367]
With 1.22.1 the openid-callback is fixed (#4327). But the matrix-callback in the next step has the same issue:

<img width="1127" alt="Screenshot 2024-10-30 at 08 10 35" src="https://github.com/user-attachments/assets/12f2bc30-9b9f-42bc-9819-38be66cce0be">

It is still unclear why this happen only in my setup. But all my browsers do not work. Chrome and Firefox are showing the text content and safari offers the content to download. And I can see that there is no content/type response header.

**Comment by moufmouf** [comment]
Hey @klauserber ,

It happened also on mine when I migrated from Traefik 2 to Traefik 3. I have absolutely no idea why.

The issue is fixed here: https://github.com/workadventure/workadventure/pull/4377
It is not tagged yet, but the master branch has the fix.
