### ISSUE TITLE
[Redesign] Button Icon and Button Text doesn't work

### ISSUE THREAD

**Issue by HugoAverty** [workadventure/workadventure#4416]
On : 
http://play.workadventure.localhost/_/5piixbabvxd/hugoaverty.github.io/wa-ui-test/map.tmj

![Screenshot 2024-11-27 à 11 04 24](https://github.com/user-attachments/assets/8f9d135d-ff46-41d5-8002-52e58ba27cce)

**Comment by moufmouf** [comment]
Fixed
