### ISSUE TITLE
[Redesign] Banner doesn't work

### ISSUE THREAD

**Issue by HugoAverty** [workadventure/workadventure#4417]
On : http://play.workadventure.localhost/_/5piixbabvxd/hugoaverty.github.io/wa-ui-test/map.tmj
![Screenshot 2024-11-27 à 11 05 54](https://github.com/user-attachments/assets/6e16e987-ed87-4dec-a0fd-da9f889a85a5)

**Comment by moufmouf** [comment]
Fixed
