### ISSUE TITLE
[Redesign] Repeated copying of the cowebsite link crashes cowebsites

### ISSUE THREAD

**Issue by HugoAverty** [workadventure/workadventure#4421]
![Screenshot 2024-11-27 à 11 12 00](https://github.com/user-attachments/assets/dd396a72-2d0b-41f8-bad1-c8e9e9f20d2c)

Try :
![Screenshot 2024-11-27 à 11 12 18](https://github.com/user-attachments/assets/df73890e-95fc-4097-833e-be94d44241c9)
Copy button many time

When I leave Cowebsite zone, doesn't close

**Comment by moufmouf** [comment]
Closed in #4436
