### ISSUE TITLE
Auto follow other user

### ISSUE THREAD

**Issue by rorist** [workadventure/workadventure#791]
Hello,

When giving a tour it's an art to walk slow enough to keep to local video chat open, it would be nice to be able to auto-follow an other player.

Thanks for the awesome software, it helps us a lot at work as well as in our association.

**Comment by Jacques-Olivier-Farcy** [comment]
Hi,

I think it is a really good idea !
I hope it is technically possible.

**Comment by plan5** [comment]
An alternative solution might be an option to lock on to another user so you don't lose connection when the other user walks away.
For example, 
1. Player A approaches Player B.
2. UI shows a button to offer locking connection to both.
3. Player A clicks on "lock connection" button
4. Player B sees a message "Player A wants to lock their connection with you. Accept/Reject?"
5. Player B accepts and walks away from Player A.
6. Player A and Player B can still talk to and see each other.
7. Player A and Player B see a "unlock conversation button" that ends the connection.

This would probably keep the Players from entering other conversations while lock is on.
So it would need some kind of representation (e.g. a blue circle around each player and when Player C approaches Player B or Player A, there might be a visible line between Player A and Player B and there might also be a "request access" button or so.

This would be very useful for large events.

**Comment by Jacques-Olivier-Farcy** [comment]
I talk to @moufmouf today, the best way should be to be able to be "linked" to someone eslse, so the sprite of the user B could automatically follow the sprite of the user A, and then will be kept in the connection circle.

**Comment by Lurkars** [comment]
I want to bump this feature again. I would really like an auto-follow function, because it solves the problem of loosing chat while moving and as extra feature, if you want to show someone the map, walking around with auto-follow would make it much easier. Due to the "Block User" function, annoying followers can just be blocked. With the already existing companion code, the feature shouldn't be too hard to implement. Only important question is where to toggle follow of a player.

**Comment by moufmouf** [comment]
True, the feature would be very interesting.

>  Only important question is where to toggle follow of a player.

... and can a user decide to ask another user to follow him/her?

**Comment by Kharhamel** [comment]
Copy pasting my comment from another issue:
```
Auto follow isn't too bad to implement in practice, the game already listens to the position changes of every player next to you, so all you have to do calculate the movement vector and apply to your own character. It is a bit wonky because of the latency between your target's move and yours but it still works.
Alternatively I could try accelerating the player toward its target but it might be harder to notify the server of your changes of position.

To me, it is more of a UI issue. How do you activate it and how do you desactivate it?
Following another player takes away soem of the control you have on your own character, so it needs to be activated by something very explicit (I think about a menu attached to a user on right click with an option 'Follow')

And for breaking the follow, it needs to be easy and quick for the same reason (people don't like loosing control and wants to get it back easily). I though about breaking the follow when you input a movement , but this means that you cannot use your movement keys to adjust your position/trajectory while still following. And clicking on a contextual menu might be not ergonomic because the followed player will be moving.

**Comment by Lurkars** [comment]
Yea in general I had the same thoughts. Maybe the radial menu is a good accretion menu for other players: auto-follow, blocking, show visit-card are at least 3 options i can think of. Also thought that quitting can be done by using movement keys, but you're right, that it may be needed/intuitive for adjust movement, so maybe moving away a certain threshold can stop following, like moving hard in the opposite direction, but besides I am unsure about how intuitive this is, I also don't know if it is that easy to implement, at least to feel good and usable.

**Comment by moufmouf** [comment]
Also copying my comment from #1304 

:+1: for the autofollow option (already said that).

I agree it is more of a UI issue than anything else.

> Following another player takes away soem of the control you have on your own character, so it needs to be activated by something very explicit (I think about a menu attached to a user on right click with an option 'Follow')

Now that I think about it, I wonder if we should not, on the contrary, be triggered by the person who wants to "lead" the party.

I mean, quite often, if someone is new to WorkAdventure, and you want him/her to follow you, it will be hard to explain: "ok, right click on me and click the "follow" button".

Instead, we could have a big "Lead" button (I'm not sure about the wording) that would appear when in a bubble. Anyone inside the bubble would automatically auto-follow your character.
As long as it is easy to stop following someone (by touching any input key), I think we should be ok. Most users are well intended, and we already have a ban/ignore feature that can be used to ignore people that would be abusing the feature.

Thoughts?

**Comment by ValdoTR** [comment]
@moufmouf I think you can close that issue now :p

**Comment by moufmouf** [comment]
Definitely! It's been implemented for 2 years now! :laughing:
