### ISSUE TITLE
[Feature Request] Add playVideo

### ISSUE THREAD

**Issue by plan5** [workadventure/workadventure#868]
It would be great to have a playVideo special zone that displays video as an overlay.
It can be added above the audio volume bar that is displayed in playAudio zones.

This has been done already here: https://github.com/DigitaleGesellschaft/workadventure/tree/videoplayer

However, I cannot get it to run based on the published code and I received no feedback on this issue from digitalegesellschaft:   https://github.com/DigitaleGesellschaft/workadventure/issues/39. Something seems to be missing.

It was available during an event, I'm adding a screenshot.
![screenshot](https://user-images.githubusercontent.com/30434574/113355976-e0497580-9341-11eb-959d-04505c11ae82.png)

**Comment by pizkaz** [comment]
This feature is working (it seems) in our [experimental community edition](https://github.com/workadventure-xce/workadventure-xce). When it was tested a little further, we will create a pull request.

**Comment by plan5** [comment]
> This feature is working (it seems) in our [experimental community edition](https://github.com/workadventure-xce/workadventure-xce). When it was tested a little further, we will create a pull request.

It's not working on my server with your edition either. 
Do you have any advice for debugging this? 
I've cloned your repo and run it with the docker-compose.yaml from https://wiki.techinc.nl/Work-Adventure/install

**Comment by plan5** [comment]
> You should take a look at https://github.com/workadventure-xce/workadventure-xce/tree/xce/contrib/docker
> What you need might just be in there. ;-)

Thanks!
